config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'

  get "/main/index"

  get "login" => "sessions#login"
  get "location" => "sessions#location"
  post "location" => "sessions#add_location"
  post "login" => "sessions#create_session"
  get "/logout" => "sessions#destroy"

  get "/main/report_select"
  post "/main/income_summary"
  post "/main/cashier_summary"
  post "/main/daily_cash_summary"
  get "/main/daily_cash_summary"
  get "/main/print_daily_cash_summary"
  post "/main/census_report"
  get 'print_refund' => "deposits#print_refund"

  # Route for handling general options page
  #get 'order_entries/general_options', to: 'order_entries#general_options'

  # Route for creating an order entry
  #post 'order_entries', to: 'order_entries#create'
  

  resources :patients do
    collection do
      get 'search'
      get 'ajax_search'
      get 'given_names'
      get 'family_names'
      get 'district'
      get 'traditional_authority'
      get 'village'
      get 'nationality'
      get 'landmark'
      get 'country'
      get 'patient_demographics(/:id)', action: :patient_demographics
      post 'process_result'
      post 'process_confirmation'
      post 'ajax_process_result'
      post 'confirm_demographics'
      post 'ajax_process_data'
      get 'patient_not_found(/:id)', action: :patient_not_found
      post 'patient_not_found(/:id)', action: :patient_not_found
      get 'print_national_id'
      get 'patient_by_id(/:id)', action: :patient_by_id
    end
    resources :order_entries
    resources :patient_accounts
    resources :deposits do
      collection do
        get 'reclaim_deposit'
      end
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
    end
  end
  resources :user_properties
  resources :service_types
  resources :medical_scheme_providers do
    resources :medical_scheme
    collection do
      get 'suggestions'
    end
  end
  resources :sessions
  resources :users do
    collection do
      get 'roles'
    end
  end
  resources :order_entries do
    collection do
      post 'void'
    end
  end
  resources :services do
    collection do
      get 'suggestions'
    end
    resources :service_prices
  end
  resources :order_payments do
    collection do
      get 'print_receipt'
      post 'void'
    end
  end

end

app/models/service.rb
class Service < ActiveRecord::Base

  #default_scope {-> {order 'rank ASC, name ASC' }}
  default_scope { where(voided: false) }
  default_scope { order('rank ASC, name ASC') }
  has_many :service_prices
  has_many :service_price_histories
  belongs_to :service_type
  attr_accessor :category

  before_create :before_create

  def get_price(location)
    self.service_prices.select(:price,:price_id).where(price_type: location).first rescue nil
  end

  def before_create
    self.service_type_id= self.category if self.service_type_id.blank?
  end
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  #default_scope {-> { where "#{self.table_name}.retired = false" }}
  default_scope { where(retired: false) }
  has_many :services
  has_many :service_panels

  def top_ten_services
    self.services.select(:name).limit(10).collect{|x| x.name}
  end
  def child
    self.services.select(:name).where(service_id: 3).collect{|x| x.name}
  end
  def male
    self.services.select(:name).where(service_id: [1,6]).collect{|x| x.name}
  end
  def female
    self.services.select(:name).where(service_id: [2,4,5,6]).collect{|x| x.name}
  end
  def number_of_services
    self.services.select("count(service_id) as count").first.count
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end

  def new
    render :layout => 'touch'
  end

  def create
    @new_service = Service.create(service_params)
    (params[:service_price] || []).each do |type, price|
      service_price = ServicePrice.new()
      service_price.price_type = type
      service_price.service_id = @new_service.id
      service_price.price = price[:price]
      service_price.creator = params[:service][:creator]
      service_price.updated_by = params[:service][:creator]
      service_price.save
    end
    redirect_to @new_service
  end

  def update
    @new_service = Service.find(params[:id])
    @new_service.update(service_params)
    (params[:service_price] || []).each do |type, price|
      service_price = ServicePrice.new()
      service_price.price_type = type
      service_price.service_id = @new_service.id
      service_price.price = price[:price]
      service_price.creator = params[:creator]
      service_price.updated_by = params[:creator]
      service_price.save
    end
    redirect_to @new_service
  end

  def edit
    @service = Service.find(params[:id])
    render :layout => 'touch'
  end

  def destroy

  end

  def suggestions
    type = ServiceType.find_by_name(params[:category])
    services = Service.select(:name).where('service_type_id = ? and name like (?)',
                                           type.id, "%#{params[:search_string]}%" ).map do |v|
      "<li value=\"#{v.name}\">#{v.name}</li>"
    end

    render :body => services.join('') and return
  end

  private
  def service_params
    params.require(:service).permit(:category,:name, :creator)
  end
end

app/helpers/services_helper.rb
module ServicesHelper
  def category_options(selected_category = [])
    options_array = [[]] + ServiceType.select(:service_type_id,:name).collect{|x| [x.name,x.service_type_id]}
    options_for_select(options_array, selected_category)
  end

end

app/views/services/edit.html.erb
<script type="text/javascript">
    tt_cancel_destination = "/services"
</script>

<%= form_for :service, :method => "PATCH" ,:url => service_path  do |f| %>

    <%= text_field_tag "service[name]", @service.name,
                       {:helptext => "Enter name of new service"}  %>

    <%= select_tag "service[category]", category_options,
                   {:helptext => "Select service category",
                    :doublepane => 'false'} %>

    <%= text_field_tag "service_price[general][price]", nil,
                       {:field_type => "number",
                        :tt_pageStyleClass => "NumbersOnly",
                        :helptext => "Enter general price for new service"}  %>

    <%= text_field_tag "service_price[private][price]", nil,
                       {:field_type => "number",
                        :tt_pageStyleClass => "NumbersOnly",
                        :helptext => "Enter private price for new service"}  %>

    <%= hidden_field_tag "creator", current_user.id %>

<% end %>

app/views/services/index.html.erb
<style>
  .dataTables_filter{
    position: absolute;
    width: 50vw;
    top: 3vh;
    left: 50vw;
    font-size: 1.5em;
  }
  input{
    font-size: 1.5em;
  }
</style>

<%= javascript_include_tag 'jquery.dataTables.min.js' %>
<script type="text/javascript">
    // Styling the table with datatables library
    $(document).ready(function() {
        $('#serviceTypes').DataTable({"bLengthChange": false,
            "bDestroy": true,
            "pageLength":7
        });
        search_box = $('#serviceTypes').dataTable()
        search = document.getElementById('serviceTypes_filter').children[0].children[0];
        document.getElementById('serviceTypes_filter').setAttribute("onmousedown","showKeyboard();");
        keyboard = document.getElementsByClassName("keypad")[0]
        showAlphaKeypad();

    } );

    function showKeyboard(){
        console.log("show keyboard")
        key = document.getElementById("keypad")
        if(key.style.display == 'none' || key.style.display == ""){
            key.style.display = "inline";
            return
        }

        key.style.display = "none";
    }
</script>

<div class="section-header">
  Service
</div>

<div style="height: 70vh; width: 100vw;">
  <table class="dashboard-main" id="serviceTypes" style="width: 100vw;">
    <thead>
    <th style="text-align: left;padding-left: 5px;">Name</th>
    <th>Category</th>
    <th>Actions</th>
    </thead>
    <tbody>
    <% (@services || []).each do |service| %>
        <tr>
          <td style="text-align: left;padding-left: 5px;"><%= service.name%></td>
          <td><%= service.service_type.name %></td>
          <td> <%= link_to 'View', "/services/#{service.id}" %> <%= link_to 'Edit', "/services/#{service.id}/edit" %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div id="keypad">
  <span class="keypad"></span>
</div>

<div class="footer">
  <button class="button green" style="float: right;" onmousedown="window.location='/'">Finish</button>
  <button class="button blue" style="float: right;" onmousedown="window.location='/services/new'">Add Service</button>
</div>

app/views/services/new.html.erb
<script type="text/javascript">
    tt_cancel_destination = "/services"
</script>

<%= form_for :service, :method => "POST" ,:url => services_path  do |f| %>

    <%= text_field_tag "service[name]", nil,
                       {:helptext => "Enter name of new service"}  %>

    <%= select_tag "service[category]", category_options,
                   {:helptext => "Select service category",
                    :doublepane => 'false'} %>

    <%= text_field_tag "service_price[general][price]", nil,
                       {:field_type => "number",
                        :tt_pageStyleClass => "NumbersOnly",
                        :helptext => "Enter general price for new service"}  %>

    <%= text_field_tag "service_price[private][price]", nil,
                       {:field_type => "number",
                        :tt_pageStyleClass => "NumbersOnly",
                        :helptext => "Enter private price for new service"}  %>

    <%= hidden_field_tag "service[creator]", current_user.id %>

<% end %>

app/views/services/show.html.erb
<div class="section-header">
  <div style="display: table-cell;text-align: left; width: inherit;">
    <b>Service :</b> <%= @service.name %>
  </div>
  <div style="display: table-cell;text-align: center; width: 30vw;border: 1px solid cornflowerblue;">
    <span style="font-size: 0.8em;">General Price</span>
    <div style="display: table-cell;vertical-align: middle;width: 60%;font-size: 0.5em;padding-left: 5px;">
      <%= "#{local_currency(@service.get_price("General").price) rescue ''}" %>
    </div>
    <div style="display: table-cell;vertical-align: middle;text-align: right;width: 40%;">
      <img  src="/assets/edit.png" onmousedown="window.location='/services/<%= @service.id %>/service_prices/new?type=general'" title="Edit Category">
    </div>
  </div>
  <div style="display: table-cell;text-align: center; width: 30vw;border: 1px solid cornflowerblue;">
    <span style="font-size: 0.8em;">Private Price</span>
    <div style="display: table-cell;vertical-align: middle;width: 60%;font-size: 0.5em;padding-left: 5px;">
      <%= "#{local_currency(@service.get_price("Private").price) rescue ''}" %>
    </div>
    <div style="display: table-cell;vertical-align: middle;text-align: right;width: 40%;">
      <img  src="/assets/edit.png" onmousedown="window.location='/services/<%= @service.id %>/service_prices/new?type=private'" title="Edit Category">
    </div>
  </div>
</div>
<div style="height: 70vh;">
  <table class="dashboard-main" id="serviceTypes" >
    <thead>
      <tr>
        <th style="text-align: left;padding-left: 5px;">Price Type</th>
        <th>Price</th>
        <th>Active From</th>
        <th>Active To</th>
        <th>Updated By</th>
      </tr>
    </thead>
    <tbody>
    <% (@service.service_price_histories || []).each do |history| %>
        <tr>
          <td style="text-align: left;padding-left: 5px;"><%= history.price_type%></td>
          <td><%= local_currency(history.price) %></td>
          <td><%= history.active_from.strftime('%d %b, %Y') %></td>
          <td><%= history.active_to.strftime('%d %b, %Y') rescue '' %></td>
          <td><%= history.user.name %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<div class="footer">
  <button class="button green" style="float: right;" onmousedown="window.location='/services'">Finish</button>
</div>