config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'

  get "/main/index"

  get "login" => "sessions#login"
  get "location" => "sessions#location"
  post "location" => "sessions#add_location"
  post "login" => "sessions#create_session"
  get "/logout" => "sessions#destroy"

  get "/main/report_select"
  post "/main/income_summary"
  post "/main/cashier_summary"
  post "/main/daily_cash_summary"
  get "/main/daily_cash_summary"
  get "/main/print_daily_cash_summary"
  post "/main/census_report"
  get 'print_refund' => "deposits#print_refund"

  # Route for handling general options page
  #get 'order_entries/general_options', to: 'order_entries#general_options'

  # Route for creating an order entry
  #post 'order_entries', to: 'order_entries#create'
  

  resources :patients do
    collection do
      get 'search'
      get 'ajax_search'
      get 'given_names'
      get 'family_names'
      get 'district'
      get 'traditional_authority'
      get 'village'
      get 'nationality'
      get 'landmark'
      get 'country'
      get 'patient_demographics(/:id)', action: :patient_demographics
      post 'process_result'
      post 'process_confirmation'
      post 'ajax_process_result'
      post 'confirm_demographics'
      post 'ajax_process_data'
      get 'patient_not_found(/:id)', action: :patient_not_found
      post 'patient_not_found(/:id)', action: :patient_not_found
      get 'print_national_id'
      get 'patient_by_id(/:id)', action: :patient_by_id
    end
    resources :order_entries
    resources :patient_accounts
    resources :deposits do
      collection do
        get 'reclaim_deposit'
      end
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
    end
  end
  resources :user_properties
  resources :service_types
  resources :medical_scheme_providers do
    resources :medical_scheme
    collection do
      get 'suggestions'
    end
  end
  resources :sessions
  resources :users do
    collection do
      get 'roles'
    end
  end
  resources :order_entries do
    collection do
      post 'void'
    end
  end
  resources :services do
    collection do
      get 'suggestions'
    end
    resources :service_prices
  end
  resources :order_payments do
    collection do
      get 'print_receipt'
      post 'void'
    end
  end

end

app/controllers/service_types_controller.rb
class ServiceTypesController < ApplicationController
  def index
    @categories = ServiceType.all
  end

  def show
    @category = ServiceType.find(params[:id])
  end

  def new
    render :layout => 'touch'
  end

  def create

    new_service_type = ServiceType.where(name: params[:service_type][:name]).first_or_initialize
    new_service_type.creator = params[:service_type][:creator]
    new_service_type.save
    redirect_to "/service_types" and return
  end

  def update
    edit_service_type = ServiceType.find(params[:id])
    edit_service_type.name = params[:service_type][:name]
    edit_service_type.save
    redirect_to "/service_types" and return
  end

  def edit
    @service_type = ServiceType.find(params[:id])
    render :layout => 'touch'
  end

  def destroy

  end

end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/views/service_types/edit.html.erb
<script type="text/javascript">
    tt_cancel_destination = "/service_types %>"
</script>

<%= form_for :service_types, :method => "PATCH" ,:url => service_type_path  do |f| %>

    <%= text_field_tag "service_type[name]", @service_type.name,
                       {
                           :helptext => "Enter new name of category"}  %>

    <%= hidden_field_tag "service_type[creator]", current_user.id %>

<% end %>

app/views/service_types/index.html.erb
<style>
  .dataTables_filter{
    position: absolute;
    width: 50vw;
    top: 3vh;
    left: 50vw;
    font-size: 1.5em;
  }
input{
  font-size: 1.5em;
}
</style>

<%= javascript_include_tag 'jquery.dataTables.min.js' %>
<script type="text/javascript">
    // Styling the table with datatables library
    $(document).ready(function() {
        $('#serviceTypes').DataTable({"bLengthChange": false,
            "bDestroy": true,
            "pageLength":7
        });
        search_box = $('#serviceTypes').dataTable()
        search = document.getElementById('serviceTypes_filter').children[0].children[0];
        document.getElementById('serviceTypes_filter').setAttribute("onmousedown","showKeyboard();");
        keyboard = document.getElementsByClassName("keypad")[0]
        showAlphaKeypad();

    } );

    function showKeyboard(){
        console.log("show keyboard")
        key = document.getElementById("keypad")
        if(key.style.display == 'none' || key.style.display == ""){
            key.style.display = "inline";
            return
        }

        key.style.display = "none";
    }
</script>

<div class="section-header">
  Service Categories
</div>

<div style="height: 70vh; width: 100vw;">
  <table class="dashboard-main" id="serviceTypes" style="width: 100vw;">
    <thead>
      <th style="text-align: left;padding-left: 5px;">Name</th>
      <th>Number of Services</th>
      <th>Actions</th>
    </thead>
    <tbody>
    <% (@categories || []).each do |category| %>
      <tr>
        <td style="text-align: left;padding-left: 5px;"><%= category.name%></td>
        <td><%= category.number_of_services %></td>
        <td style="text-align: center;">
          <img  src="/assets/edit.png" onmousedown="window.location='/service_types/<%= category.id %>/edit'" title="Edit Category">
          <img  src="/assets/delete.png" onmousedown="window.location='/service_types/<%= category.id %>/edit'" title="Edit Category">
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<div id="keypad">
 <span class="keypad"></span>
</div>

<div class="footer">
  <button class="button green" style="float: right;" onmousedown="window.location='/'">Finish</button>
  <!--<button class="button blue" style="float: right;" onmousedown="window.location='/service_types/new'">Add Category</button> //-->
</div>

app/views/service_types/new.html.erb
<script type="text/javascript">
    tt_cancel_destination = "/service_types %>"
</script>

<%= form_for :service_types, :method => "POST" ,:url => service_types_path  do |f| %>

    <%= text_field_tag "service_type[name]", nil,
                       {
                        :helptext => "Enter name of new category"}  %>

    <%= hidden_field_tag "service_type[creator]", current_user.id %>

<% end %>

app/views/service_types/show.html.erb
<div class="section-header" >
  Service category : <%= @category.name.titleize %>
</div>
<div style="height: 70vh; width: 100vw;">

</div>

<div class="footer">
  <button class="green" style="float: right;" onmousedown="window.location='/service_types'">Finish</button>
</div>