config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'

  get "/main/index"

  get "login" => "sessions#login"
  get "location" => "sessions#location"
  post "location" => "sessions#add_location"
  post "login" => "sessions#create_session"
  get "/logout" => "sessions#destroy"

  get "/main/report_select"
  post "/main/income_summary"
  post "/main/cashier_summary"
  post "/main/daily_cash_summary"
  get "/main/daily_cash_summary"
  get "/main/print_daily_cash_summary"
  post "/main/census_report"
  get 'print_refund' => "deposits#print_refund"

  # Route for handling general options page
  #get 'order_entries/general_options', to: 'order_entries#general_options'

  # Route for creating an order entry
  #post 'order_entries', to: 'order_entries#create'
  

  resources :patients do
    collection do
      get 'search'
      get 'ajax_search'
      get 'given_names'
      get 'family_names'
      get 'district'
      get 'traditional_authority'
      get 'village'
      get 'nationality'
      get 'landmark'
      get 'country'
      get 'patient_demographics(/:id)', action: :patient_demographics
      post 'process_result'
      post 'process_confirmation'
      post 'ajax_process_result'
      post 'confirm_demographics'
      post 'ajax_process_data'
      get 'patient_not_found(/:id)', action: :patient_not_found
      post 'patient_not_found(/:id)', action: :patient_not_found
      get 'print_national_id'
      get 'patient_by_id(/:id)', action: :patient_by_id
    end
    resources :order_entries
    resources :patient_accounts
    resources :deposits do
      collection do
        get 'reclaim_deposit'
      end
    end
  end

  resources :locations do
    collection do
      get 'search'
      get 'print_label'
    end
  end
  resources :user_properties
  resources :service_types
  resources :medical_scheme_providers do
    resources :medical_scheme
    collection do
      get 'suggestions'
    end
  end
  resources :sessions
  resources :users do
    collection do
      get 'roles'
    end
  end
  resources :order_entries do
    collection do
      post 'void'
    end
  end
  resources :services do
    collection do
      get 'suggestions'
    end
    resources :service_prices
  end
  resources :order_payments do
    collection do
      get 'print_receipt'
      post 'void'
    end
  end

end

app/models/deposit.rb
class Deposit < ActiveRecord::Base
  #default_scope {-> { where "#{self.table_name}.voided = false" }}
  belongs_to :patient, :foreign_key => :patient_id
  belongs_to :creator, class_name: 'User', :foreign_key => :creator

  def receipt_number
    "#{(self.id).to_s.rjust(6, '0')}"
  end
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  def new
    render layout: 'touch'
  end

  def create

    new_deposit = Deposit.new()
    new_deposit.amount_received= params[:deposit][:amount_received]
    new_deposit.amount_available= params[:deposit][:amount_received]
    new_deposit.creator = User.find_by_user_id(params[:deposit][:creator])
    new_deposit.patient_id= params[:deposit][:patient_id]
    new_deposit.save

    if new_deposit.errors.blank?
      print_and_redirect("/patients/#{params[:patient_id]}/deposits/#{new_deposit.id}",
                         "/patients/#{params[:patient_id]}")

    else
      redirect_to "/patients/#{params[:patient_id]}"
    end

  end

  def index
    @patient = Patient.find(params[:patient_id])
    @deposits = Deposit.where(patient_id: params[:patient_id]).order("amount_available DESC, created_at DESC")
    @amount = 0
    (@deposits || []).each do |deposit|
      @amount += deposit.amount_available
    end
  end

  def show
    print_string = Misc.print_deposit_receipt(params[:id])

    send_data(print_string,:type=>"application/label; charset=utf-8", :stream=> false,
              :filename=>"#{(0..8).map { (65 + rand(26)).chr }.join}.lbs", :disposition => "inline")
  end

  def reclaim_deposit

    @redirect_url = "/patients/#{params[:patient_id]}/deposits"
    deposits = Deposit.where('patient_id = ? AND amount_available > ?', params[:patient_id],0)

    redirect_to @redirect_url if deposits.blank?

    patient = Patient.find_by_patient_id(params[:patient_id])
    patient_name = patient.full_name
    cashier_name = current_user.name
    amount_received =  0
    balance = 0
    amount_used = 0

    (deposits || []).each do |deposit|
      balance += deposit.amount_available
      amount_used += (deposit.amount_received - deposit.amount_available)
      amount_received += deposit.amount_received
      deposit.amount_available = 0
      deposit.updated_by = current_user.id
      deposit.save
    end
    print_path = "/print_refund?cashier_name=#{cashier_name}&balance=#{balance}&amount_used=#{amount_used}&amount_received=#{amount_received}&balance=#{balance}&patient_name=#{patient_name}"
    print_and_redirect(print_path, "/patients/#{params[:patient_id]}/deposits")

  end

  def print_refund
    print_string = Misc.print_refund_receipt(params)
    send_data(print_string,:type=>"application/label; charset=utf-8", :stream=> false,
              :filename=>"#{(0..8).map { (65 + rand(26)).chr }.join}.lbs", :disposition => "inline")

  end

  private

  def deposit_params
    params.require(:deposit).permit(:amount_received,:patient_id, :creator)
  end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/create.html.erb
<html>
<style>
  body{
    font-family: "Nimbus Sans L", "Arial Narrow", sans-serif;
  }


  <% if @show_next_button %>
  .page_button {
    display:block;
    font-size: 0.8em;
    color: black;
    background-color: lightgray;
    margin: 15px;
    border: 3px outset gray;
    -moz-user-select:none;
    width: 100px;
    height: 70px;
    text-align: center;
  }

  #filing_info {
    font-size:25px;
    -moz-user-select:none;
  }
  #patients_info_div{
    left:28px;
    position:absolute;
    top:0px;
    font-size:17;
    -moz-user-select:none;
  }
  td , th {
    text-align:center;
    border: 20px solid white;
    padding: 10px;
  }

  .filing_instraction {
    text-align:left;
  }

  .old_label {
    background-color:#FFFF99;
  }

  .new_label {
    background-color:lightgreen;
  }

  .active_heading {
    background-color:black;
    color:white;
  }

  #footer {
    background-color: #333333;
    bottom: 0;
    color: #CADCEA;
    height: 80px;
    overflow: hidden;
    padding-right: 20px;
    position: absolute;
    width: 98%;
  }

  <%end%>
</style>

<script>


    function done() {
        document.location = "<%=@redirect_url%>"
    }
</script>



<% if not @show_next_button %>
    <body>
    <br/><br/><br/>
    <center><h1><%=h @message %></h1></center>
    <iframe src="<%= @print_url %>" style='display:none'></iframe>
    </body>
    <script>
        setTimeout(redirect, 1000);
        function redirect(){
            document.location = '<%= @redirect_url %>'
        }
    </script>
<%else%>
    <body onload="setAttributes();">
    <%=@message%>
    <iframe src="/" style='display:none'></iframe>
    </body>
<%end%>
</html>

app/views/deposits/index.html.erb
<div id="myModal" class="modal">

  <!-- Modal content -->
  <div class="dialogMsg">
    <div style="display: table-row">
      <div style="display: table-cell; text-align: center;">
        &nbsp;
      </div>
    </div>
    <div style="display: table-row">
      <div style="display: table-cell; text-align: center;">
        <h2 id="message">Are you sure you want to reclaim the deposit?</h2>
      </div>
    </div>
    <div style="display: table-row">
      <div style="display: table-cell; text-align: center;">
        <button onMouseDown="window.location='/patients/<%=@patient.id%>/deposits/reclaim_deposit'"><span>Yes</span></button>
        <button onMouseDown="hideModal()"><span>Cancel</span></button>
      </div>
    </div>
  </div>
</div>

<div id="header" style="height: 15vh; width:98vw;margin-top:1vh; margin-left: auto;margin-right: auto;">
  <div style="display: table-row">
    <div class="header-cell" style="display: table-cell; width:98vw;vertical-align: middle;height: 15vh;">
      <div style="display: table;width: 98%;margin-left: auto;margin-right: auto;">
        <div style="display: table-cell; width: 10%;margin-left: auto;margin-right: auto;">
          <div class="<%=@patient.sex.downcase%>">
            <img src="/assets/<%=@patient.sex.downcase%>.png">
          </div>
        </div>
        <div style="display: table-cell; width: 90%;margin-left: auto;margin-right: auto;vertical-align: middle;">
          <div style="display: table;width: 98%;margin-left: auto;margin-right: auto;">
            <div style="display: table-row; ">
              <div class="header-content-cell"><b>Name</b></div>
              <div class="header-content-cell" style="width: 45%;"><%= @patient.full_name %></div>
              <div class="header-content-cell"><b>Age</b></div>
              <div class="header-content-cell"><%= @patient.person.display_age %></div>
            </div>
            <div style="display: table-row; ">
              <div class="header-content-cell"><b>National ID</b></div>
              <div class="header-content-cell"><%= Misc.dash_formatter(@patient.national_id) %></div>
              <div class="header-content-cell"><b>Health insurance</b></div>
              <div class="header-content-cell"><%= @patient.health_insurance %></div>
            </div>
            <div style="display: table-row; ">
              <div class="header-content-cell"><b>Residence</b></div>
              <div class="header-content-cell"><%= @patient.current_address %></div>
              <div class="header-content-cell"><b>Scheme Number</b></div>
              <div class="header-content-cell"><%= @patient.scheme_num %></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="main" style="height: 65vh;width: 98vw; padding: 5px; margin-left: auto; margin-right: auto;overflow-y: auto;overflow-x: hidden;border: 2px solid #336699;">
  <% if @deposits.blank?  %>
    <h3>No deposits made by this patient</h3>
  <% else %>
      <table class="dashboard-main" border="2">
        <thead>
        <tr>
          <th style="text-align: left;">Date Received</th>
          <th style="text-align: left;">Received By</th>
          <th style="text-align: right;padding-right: 10px;">Amount Received</th>
          <th style="text-align: right;padding-right: 10px;">Amount Remaining</th>
          <th>Action</th>
        </tr>
        </thead>
        <tbody>
        <% (@deposits || []).each do |deposit| %>
          <tr>
            <td style="text-align: left;padding-left: 5px;"><%= deposit.created_at.strftime('%d %b, %Y') %></td>
            <td style="text-align: left;"><%= deposit.creator.name %></td>
            <td style="text-align: right;padding-right: 5px;"><%= local_currency(deposit.amount_received) %></td>
            <td style="text-align: right;padding-right: 5px;"><%= local_currency(deposit.amount_available) %></td>
            <td style="border: 1px solid #000000; background-color: #fefefe;">
            <% if deposit.amount_available > 0 %>

                  <img src="/assets/delete.png" style="vertical-align: middle;" title="Void Item"
                       onmousedown="confirmAction('/order_payments/void', 'LINK')">

            <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  <% end %>
</div>

<div class="footer">
  <button class="green" style="float: right;" onmousedown="window.location='/patients/<%= params[:patient_id] %>'">Finish</button>
  <% if @amount > 0%>
      <button style="float: right;" onmousedown="showModal()">Reclaim Deposit</button>
  <% end %>
</div>

<script type="text/javascript">
  var modal = document.getElementById('myModal');

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }
</script>

app/views/deposits/new.html.erb
<script type="text/javascript">
    tt_cancel_destination = "/patients/<%= params[:patient_id] %>"
</script>

<%= form_for :deposit, :method => "POST" ,:url => patient_deposits_path  do |f| %>

    <%= text_field_tag "deposit[amount_received]", nil,
                       {
                        :field_type => "number",
                        :tt_pageStyleClass => "NumbersOnly",
                        :helptext => "Enter amount deposited"}  %>


    <%= hidden_field_tag "deposit[creator]", current_user.id %>
    <%= hidden_field_tag "deposit[patient_id]", params[:patient_id] %>
<% end %>

app/views/deposits/reclaim_deposit.html.erb
<html>
<style>
  body{
    font-family: "Nimbus Sans L", "Arial Narrow", sans-serif;
  }


  <% if @show_next_button %>
  .page_button {
    display:block;
    font-size: 0.8em;
    color: black;
    background-color: lightgray;
    margin: 15px;
    border: 3px outset gray;
    -moz-user-select:none;
    width: 100px;
    height: 70px;
    text-align: center;
  }

  #filing_info {
    font-size:25px;
    -moz-user-select:none;
  }
  #patients_info_div{
    left:28px;
    position:absolute;
    top:0px;
    font-size:17;
    -moz-user-select:none;
  }
  td , th {
    text-align:center;
    border: 20px solid white;
    padding: 10px;
  }

  .filing_instraction {
    text-align:left;
  }

  .old_label {
    background-color:#FFFF99;
  }

  .new_label {
    background-color:lightgreen;
  }

  .active_heading {
    background-color:black;
    color:white;
  }

  #footer {
    background-color: #333333;
    bottom: 0;
    color: #CADCEA;
    height: 80px;
    overflow: hidden;
    padding-right: 20px;
    position: absolute;
    width: 98%;
  }

  <%end%>
</style>

<script>


  function done() {
    document.location = "<%=@redirect_url%>"
  }
</script>



<% if not @show_next_button %>
    <body>
    <br/><br/><br/>
    <center><h1><%=h @message %></h1></center>
    <iframe src="<%= @print_url %>" style='display:none'></iframe>
    </body>
    <script>
      setTimeout(redirect, 1000);
      function redirect(){
        document.location = '<%= @redirect_url %>'
      }
    </script>
<%else%>
    <body onload="setAttributes();">
    <%=@message%>
    <iframe src="/" style='display:none'></iframe>
    </body>
<%end%>
</html>